# TCL File Generated by Component Editor 18.1
# Tue May 25 15:42:41 MSK 2021
# DO NOT MODIFY


# 
# ad56x3_generator "Generator for DACs ad56x3 series" v1.0
# Shustov Aleksey (SemperAnte), semte@semte.ru 2021.05.25.15:42:41
# Simple saw generator for DAC AD56x3 with Avalon ST interface for testing purpose
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ad56x3_generator
# 
set_module_property DESCRIPTION "Simple saw generator for DAC AD56x3 with Avalon ST interface for testing purpose"
set_module_property NAME ad56x3_generator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Shustov Aleksey (SemperAnte), semte@semte.ru"
set_module_property DISPLAY_NAME "Generator for DACs ad56x3 series"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK Elaborate


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dacGenerator_hw
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dacGenerator.sv SYSTEM_VERILOG PATH dacGenerator.sv
add_fileset_file dacGenerator_hw.sv SYSTEM_VERILOG PATH dacGenerator_hw.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter SIGN_A STRING UNSIGNED
set_parameter_property SIGN_A DEFAULT_VALUE UNSIGNED
set_parameter_property SIGN_A DISPLAY_NAME SIGN_A
set_parameter_property SIGN_A TYPE STRING
set_parameter_property SIGN_A UNITS None
set_parameter_property SIGN_A HDL_PARAMETER true
set_parameter_property SIGN_A ALLOWED_RANGES {SIGNED UNSIGNED}

add_parameter SIGN_B STRING UNSIGNED
set_parameter_property SIGN_B DEFAULT_VALUE UNSIGNED
set_parameter_property SIGN_B DISPLAY_NAME SIGN_B
set_parameter_property SIGN_B TYPE STRING
set_parameter_property SIGN_B UNITS None
set_parameter_property SIGN_B HDL_PARAMETER true
set_parameter_property SIGN_B ALLOWED_RANGES {SIGNED UNSIGNED}

add_parameter DATA_WIDTH INTEGER 14
set_parameter_property DATA_WIDTH DEFAULT_VALUE 14
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH HDL_PARAMETER true
set_parameter_property DATA_WIDTH ALLOWED_RANGES {12 14 16}

add_parameter INCREASE_RATE INTEGER 1
set_parameter_property INCREASE_RATE DEFAULT_VALUE 1
set_parameter_property INCREASE_RATE DISPLAY_NAME INCREASE_RATE
set_parameter_property INCREASE_RATE TYPE INTEGER
set_parameter_property INCREASE_RATE UNITS None
set_parameter_property INCREASE_RATE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset reset Input 1


# 
# connection point gen
# 
add_interface gen avalon_streaming start
set_interface_property gen associatedClock clock
set_interface_property gen associatedReset reset
set_interface_property gen errorDescriptor ""
set_interface_property gen firstSymbolInHighOrderBits true
set_interface_property gen maxChannel 0
set_interface_property gen readyLatency 0
set_interface_property gen ENABLED true
set_interface_property gen EXPORT_OF ""
set_interface_property gen PORT_NAME_MAP ""
set_interface_property gen CMSIS_SVD_VARIABLES ""
set_interface_property gen SVD_ADDRESS_GROUP ""

add_interface_port gen aso_gen_valid valid Output 1
add_interface_port gen aso_gen_channel channel Output 1
add_interface_port gen aso_gen_data data Output DATA_WIDTH
add_interface_port gen aso_gen_ready ready Input 1

# +----------------------------------------------------------------
# | Elaborate callback
# +----------------------------------------------------------------
proc Elaborate {} {
    set In_d_width [ get_parameter_value DATA_WIDTH ]
    set_interface_property gen dataBitsPerSymbol $In_d_width
}
